cordova-rtc/cordova-plugin-iosrtc

WHO_USES_IT.md

add cordova-plugin-opentokjs to who uses it

---

WHO_USES_IT.md

PR corrected with correct ID & smaller logo

Our company Free use iosrtc

---

WHO_USES_IT.md

I've wanted to do this for a while, but our app only got published today :-)
I'd like to take the opportunity to thank you for making this plugin available for everyone to use. We couldn't have done it without you. ❤️

Add Blink for Mobile to "who uses it"

---

CHANGELOG.md
LICENSE
README.md
WHO_USES_IT.md
banner.txt
dist/cordova-plugin-iosrtc.js
docs/Building.md
extra/hooks/iosrtc-swift-support.js
extra/ios-websocket-hack.js
package.json
plugin.xml
src/PluginMediaStreamTrack.swift

Update text, links and add BasqueVoIPMafia into the equation

Repository transfer paper work

---

plugin.xml

Author field should not have the unescaped "&" character

Fix author field

---

README.md
docs/Building.md
extra/hooks/iosrtc-swift-support.js
plugin.xml
src/PluginEnumerateDevices.swift
src/PluginGetUserMedia.swift
src/PluginMediaStreamRenderer.swift
src/PluginRTCDataChannel.swift
src/iosrtcPlugin.swift

Hi, I have tried to update the plugin with a more updated version of Swift. I've also tried to apply things like hook and permissions messages automatically.

Swift 4.2 and hook update

---

CHANGELOG.md
extra/hooks/iosrtc-swift-support.js
package.json

…76045b482c48ab76bd6c61a5e28d5

restore set BUILD_VERSION to 10.2 to support changes into f73dbc

---

src/PluginRTCDTMFSender.swift

To test `bugs/insertDTMF-69` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/insertDTMF-69 --verbose
```

fix insertDtmf

---

src/PluginEnumerateDevices.swift

To test `task/getAllVideoDevices-facing-label-and-order ` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#task/getAllVideoDevices-facing-label-and-order --verbose
```

 Add English facingLabel suffix if localizedName does not match for facing detection using label, fix PluginEnumerateDevices ordered array

---

src/PluginRTCAudioController.swift
src/iosrtcPlugin.swift

To test `task/PluginRTCAudioController-setCategory` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#task/PluginRTCAudioController-setCategory --verbose
```

implement PluginRTCAudioController setCategory and use audioMode AVAudioSession.Mode.voiceChat and make initAudioDevices non-static

---

dist/cordova-plugin-iosrtc.js
js/RTCIceCandidate.js

> cordova plugin remove cordova-plugin-iosrtc --verbose
> cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/candidateToJson --verbose
> cordova platform remove ios --no-save
> cordova platform add ios --no-save

 fix possible TypeError: null is not an object (evaluating 'iceCandidateFields.foundation') due fail match candidateToJson

---

.travis.yml

Test issue reporting with ionic@6
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/483
```
export CORDOVA_VERSION=8
export ANGULAR_CLI_VERSION=8
export IONIC_VERSION=6
export CORDOVA_PLATFORM=ios
export REPO_SLUG=cordova-plugin-iosrtc
export BRANCH=master
npm install -g cordova@$CORDOVA_VERSION
npm install -g @ionic/cli@$IONIC_VERSION
npm install -g @angular/cli@$ANGULAR_CLI_VERSION
ionic start myApp blank; cd myApp;
ionic cordova platform add $CORDOVA_PLATFORM@latest --verbose
ionic cordova plugin add https://github.com/$REPO_SLUG.git#$BRANCH --verbose
ionic cordova build $CORDOVA_PLATFORM --verbose
```

enable @ionic/cli@6 travis test build

---

extra/hooks/iosrtc-swift-support.js

To test `bugs/regexp-iosrtc-swift-support` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/regexp-iosrtc-swift-support --verbose
```

fix Regex in iosrtc-swift-support.js returns wrong value

---

dist/cordova-plugin-iosrtc.js
js/RTCPeerConnection.js
js/RTCStatsResponse.js
js/iosrtc.js

To test `bugs/getStats` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/getStats --verbose
```

fix RTCPeerConnection.prototype.getStats.length to match features detection

---

docs/Building.md

Instructions updated for CocoaPods and Capacitor users in docs/Building.md

build doc for CocoaPods and Capacitor users

---

dist/cordova-plugin-iosrtc.js
js/getUserMedia.js
src/PluginRTCVideoCaptureController.swift

Errors if constraints contained an aspect ratio, and again if the device was not found.

fix: undefined references

---

src/PluginGetUserMedia.swift
src/PluginMediaStream.swift
src/PluginMediaStreamRenderer.swift
src/PluginMediaStreamTrack.swift
src/PluginRTCDTMFSender.swift
src/PluginRTCDataChannel.swift
src/PluginRTCPeerConnection.swift
src/PluginRTCPeerConnectionConfig.swift
src/PluginRTCPeerConnectionConstraints.swift
src/PluginRTCVideoCaptureController.swift
src/iosrtcPlugin.swift

fixed mixed spaces/tabs indentions
fixed empty lines containing only tabs or spaces

codestyle fixed

---

js/RTCRtpSender.js
www/cordova-plugin-iosrtc.js

Fix for dispatch event call in replace track in rtcrtpsender. Done in pre build file and generated file as requested.

Fixed event dispatch in replace track in rtcrtpsender

---

js/RTCPeerConnection.js
js/RTCRtpEncodingParameters.js
js/RTCRtpReceiver.js
js/RTCRtpSendParameters.js
js/RTCRtpSender.js
js/RTCRtpTransceiver.js
js/RTCStatsReport.js
plugin.xml
src/PluginRTCPeerConnection.swift
src/PluginRTCRtpCodecParameters.swift
src/PluginRTCRtpEncodingParameters.swift
src/PluginRTCRtpParameters.swift
src/PluginRTCRtpReceiver.swift
src/PluginRTCRtpSender.swift
src/PluginRTCRtpTransceiver.swift
src/cordova-plugin-iosrtc-Bridging-Header.h
src/iosrtcPlugin.swift
www/cordova-plugin-iosrtc.js

Provides more thorough implementation for RTCRtpTransceiver, RTCRtpReceiver and RTCRtpSender classes filling most of the missing parts.

extend transceiver/sender/receiver functionality

---

src/PluginRTCPeerConnection.swift

Started here: https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/687#issuecomment-856066258
Minimal example to reproduce issue: https://github.com/RSATom/HelloJanusAudiobridge

Fixed crash when used with Janus Audiobridge

---

js/RTCRtpSender.js
www/cordova-plugin-iosrtc.js

Added createDTMFSender for RTCRtpSender

RTCRtpSender not have DTMF properties

---

src/PluginRTCPeerConnection.swift

PluginRTCPeerConnection was referenced itself
through closure context

PluginRTCPeerConnection: cyclic reference leak fixed

---

src/PluginRTCPeerConnection.swift
src/iosrtcPlugin.swift

from signaling thread with debug WebRTC library on iOs device.

PluginRTCPeerConnection: WebRTC >=m93 asserts on access to pc

---

docs/iosrtc.md
src/PluginRTCAudioController.swift
src/iosrtcPlugin.swift
www/cordova-plugin-iosrtc.js

This change is related to https://github.com/cordova-rtc/cordova-plugin-iosrtc/discussions/766

feat: MX002-8233 add method `setDefaultAudioOutput()`
