README.md
docs/Building.md
extra/hooks/iosrtc-swift-support.js
src/PluginMediaStreamRenderer.swift
src/PluginMediaStreamTrack.swift
src/PluginRTCDataChannel.swift
src/PluginRTCPeerConnection.swift
src/PluginRTCTypes.swift
src/iosrtcPlugin.swift

Ahoi!
Thanks for making this plugin available! :heart: 
Swift 2.0 was released yesterday as part of Xcode 7.0, so it's time to upgrade! With the attached patches I could compile the iOSAppRTC example using Xcode 7 and deploy it to an iPad running iOS 9.
IMPORTANT NOTE: As of right now Apple requires applications to include Bitcode, but it has to be disabled for now since the bundled libwebrtc was built without it. I left a note about this on the documentation.

Swift 2 is here!

---

README.md
dist/cordova-plugin-iosrtc.js
docs/videoCSS.md
js/MediaStreamRenderer.js

According to [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) the padding is included, so substract it.

Fix computing video view's width and height when using padding

---

src/iosrtcPlugin.swift

Overriding init is deprecated and would require fixing when Cordova iOS
is released.

Use pluginInitialize for initializing plugin

---

dist/cordova-plugin-iosrtc.js
js/videoElementsHandler.js

This bug was being triggered if you removed the video element from the DOM and try to add it later.

Bugfix _iosrtcVideoHandled flag when removing node

---

README.md
src/PluginMediaStreamRenderer.swift
src/iosrtcPlugin.swift

Tested and working on iOS-Cordova 4.1.1. 
(I messed up the first attempt trying to figure out how to rebase my commits.)

iOS-Cordova 4 support

---

src/PluginRTCPeerConnection.swift
src/iosrtcPlugin.swift

This PR uses closure syntax to define the weak/unowned variables or self, and fixes strong reference loop bugs in setLocalDescription and setRemoteDescription.
Without this fix, calling RTCPeerConnection.close() on javascript will not correctly deallocate all underlying native objects.

Use closure syntax for weak and unowned vars.

---

README.md
extra/ios-websocket-hack.js

There's no easy way to for us to have conditional `<script>` tags for each individual platform in our `index.html`. The easiest way seems to be just to have conditional execution right in the `ios-websocket-hack.js` file itself. This way, all platforms can load the same script but only iOS Cordova will have this WS hack enabled.

WebSocket hack loads iff iOS Cordova

---

docs/videoCSS.md
src/PluginMediaStreamRenderer.swift
src/iosrtcPlugin.swift

Instead of adding the video element view as a su-view of the WebView,
add it as a subview of it's superview. This puts the WebView and the
video views at the same level (aka, they are siblings) and the layer's
zPosition is considered amongst siblings.
Since an ASCII diagram is worth a thousand images, this is the layout
before this patch:
~~~~
+-------------------------------+
|           superview           |
+-------------------------------+
+-------------------------------+
|            WebView            |
+-------------------------------+
+--------------+ +--------------+
|  videoView1  | |  videoView2  |
+--------------+ +--------------+
~~~~
And after:
~~~~
+---------------------------------------+
|                superview              |
+---------------------------------------+ …

Fix positioning video elements using z-index

---

dist/cordova-plugin-iosrtc.js
docs/BuildingLibWebRTC.md
extra/libwebrtc-objc-iosrtc-dtmf.patch
extra/libwebrtc-objc-iosrtc-misc.patch
extra/libwebrtc-objc-iosrtc.patch
js/RTCDTMFSender.js
js/RTCPeerConnection.js
plugin.xml
src/PluginRTCDTMFSender.swift
src/PluginRTCPeerConnection.swift
src/cordova-plugin-iosrtc-Bridging-Header.h
src/iosrtcPlugin.swift
src/webrtc-headers/RTCDTMFSender.h
src/webrtc-headers/RTCPeerConnection.h

(Before you jump to replying "DTMF?! heresy!" please note I have not enjoyed implementing this pull request)
So, DTMF o'clock. This PR implements the RTCDMFSender functionality through RTCPeerConnection.createDTMFSender. Yes, it's supposed to be deprecated, but Chrome is one year in and they haven't moved away from it, so here we are.
In order to get this working 4 parts were needed:
* ObjC wrapper for libWebRTC's C++ library functionality
* Swift wrapper for the ObjC code
* JS code to expose the Swift code
* Sacrificing an analog phone to the PSTN gods
I've come to call this The Onion model: layers atop layers of abstraction, and the deeper you dig, the more you cry. But it works!
I digress... @ibc please take a look. I tried to break it down into small commits for easier review. …

Implement RTCPeerConnection.createDTMFSender

---

dist/cordova-plugin-iosrtc.js
js/RTCPeerConnection.js

Replaced faulty this with self in the promise implementation of RTCPeerConnection.getStats.

Changed faulty "this" to "self" in getStats callback

---

dist/cordova-plugin-iosrtc.js
gulpfile.js
package.json

cordova-plugin-iosrtc does not currently work when I use it with "--browserify" cordova option.
For example:
```sh
cordova --browserify build ios
```
gives an error:
```sh
Error: Cannot find module './MediaStreamTrack' from '.../plugins/cordova-plugin-iosrtc/dist'
```
This PR fixes this by using "gulp-derequire" to replace "require" references.

make it compatible with "--browserify" cordova option

---

js/MediaStream.js
js/videoElementsHandler.js

It may work (or not, since I don't have an iOS device to check it).

Allow setting video.srcObject (should fix issues such as #262)

---

.eslintrc
.jscsrc
.travis.yml
CHANGELOG.md
README.md
dist/cordova-plugin-iosrtc.js
docs/Building.md
extra/hooks/iosrtc-swift-support.js
gulpfile.js
package-lock.json
package.json
plugin.xml
src/PluginEnumerateDevices.swift
src/PluginGetUserMedia.swift
src/PluginMediaStreamRenderer.swift
src/PluginRTCDataChannel.swift
src/PluginRTCPeerConnection.swift
src/iosrtcPlugin.swift

```
* Convert syntax to Swift 4.2 (#356) credit to @albanonm
* Uncomment, and fix, onGetStatsCallback closure (#305) credit to @iFeli
* Update NPM dependencies
* Add Travis build (Ionic, Cordova, Browser, Android, iOS Xcode 10.2) (https://travis-ci.org/simplyrtc/cordova-plugin-iosrtc-simplyrtc)
* Fix gulp browserify caused by old vinyl package version
* Migrate from jscs to eslint to fix vulnerabilities reported by npm audit
```
* Add Harold Thetiot in package.json contributors and README.md  Maintainers

cordova-plugin-iosrtc v5.0.0

---

src/iosrtcPlugin.swift

Simple typo I caught while looking through the changes made for Swift 4.2 support. Thanks for all of the work that went into bringing this project back up to speed.

fix typo on iosrtcPlugin.swift

---

dist/cordova-plugin-iosrtc.js
js/getUserMedia.js
package-lock.json
src/PluginEnumerateDevices.swift
src/PluginGetUserMedia.swift
src/PluginRTCPeerConnection.swift

Hello @hthetiot ,
First of all, thank you for your new role in **cordova-pluign-iosrtc**.
Secondly, _cordova-plugin-iosrtc_ provide us a limited funcionality when we think of **switch of audio and video devices**. 
Nowadays the behaviour of this plugin :
1.  The plugin only shows the default devices, I mean, the front and back camera and built-in microhphone. **Doesn't recognize bluetooth and wired devices connected**.
2. The plugin doesn't allow us to switch cameras (back and front)
3. The plugin doesn't allow us to switch microphones (built-in, bluetooth and wired microphones)
I've developed the first approach to fix this limitations:
1. In [PluginEnumerateDevices.swift  24,25 ](https://github.com/cordova-rtc/cordova-plugin-iosrtc/compare/master...CSantosM:master?diff=split#diff-5a0cc8b3 …

Switch audio and video devices support

---

dist/cordova-plugin-iosrtc.js
js/RTCPeerConnection.js

Note: this is only required if you dont use webrtc-adapter.

RTCPeerConnection.setLocalDescription() and other  methods which take SDP as input now directly accept an object

---

src/PluginEnumerateDevices.swift

Hello @hthetiot ,
This changes add the audio input priority. 
Before these changes, the Built-in Microphone was set up by default. Now, the priority established is Wired microphone > Wireless microphone > built-in microphone.
Take a look.
Regards

Estabished audio input priority

---

dist/cordova-plugin-iosrtc.js
js/videoElementsHandler.js

With the deprecation of the src attribute and not being able to use MutationObserver with srcObject, I noticed that adding a new MediaStream to a video element with a already existing srcObject (and not setting it to null in between) will result in the video displaying only a black square.
So to combat that I added a check for if the video "updated" the srcObject and if so re-renders the MediaStream.

Recognize when a video receives a new srcObject and re-render it

---

extra/renderer-and-libwebrtc-tests.js
src/PluginMediaStreamRenderer.swift

add screenStatusBarHeight to elementView.frame.y computation to fix bad position over status-bar when video.style.position.top = 0
Test Script used:
- https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/extra/renderer-and-libwebrtc-tests.js
Before 
After

[Resolved] use safeAreaLayoutGuide for ios 11 and NSLayoutConstraint for ios 10 to fix elementView bad position depending status bar visibility

---

extra/hooks/iosrtc-swift-support.js
package-lock.json
package.json

The hook fails to find the correct files/directories when the project name in config.xml contains XML entities like `&amp;` ('&' symbol).

Decode XML entities in project name in iosrtc-swift-support.js hook

---

src/PluginMediaStream.swift
src/PluginMediaStreamRenderer.swift
src/PluginMediaStreamTrack.swift
src/PluginRTCPeerConnection.swift
src/iosrtcPlugin.swift

generate unique PluginMediaStream and PluginMediaStreamTrack, keep original streamId/trackId for internal calls
To test `task/stream-track-uuid` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#task/stream-track-uuid --verbose
```

generate unique PluginMediaStream and PluginMediaStreamTrack, keep original streamId/trackId for internal calls

---

src/PluginMediaStream.swift
src/PluginMediaStreamTrack.swift
src/PluginRTCPeerConnection.swift

- fix PeerConnection removestream to use PluginMediaStream.id instead of RTCMediaStream.streamId
- suffix PluginMediaStreamTrack.id with real PluginMediaStreamTrack.streamId
- fix PeerConnection removestream to use PluginMediaStream.id instead of RTCMediaStream.streamId

Fix removeStream and add real Ids with UUID suffix to PluginMediaStream and PluginMediaStreamTrack

---

extra/renderer-and-libwebrtc-tests.js
js/EventTarget.js

To test `bugs/EventTarget` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/EventTarget --verbose
```

Missing Event.target value on iosRTC Events

---

js/RTCPeerConnection.js
src/PluginMediaStream.swift
src/PluginMediaStreamTrack.swift
src/iosrtcPlugin.swift

use UUID().uuidString preffix for PluginMediaStream and PluginMediaStreamTrack only if rtcMediaStream.streamId or rtcMediaStreamTrack.trackId start with 'janus' to fix PeerConnection.addStream|addTrack regression

use UUID().uuidString preffix for PluginMediaStream and PluginMediaStreamTrack only for Janus

---

src/PluginGetUserMedia.swift

Hello @hthetiot 
There's a bug changing the audio devices. Any changes we made, doesn't have any effect. 
The problem is that in [getUserMedia.js](https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/69bb0eaa7ec6022d289d40c311016fce1167c127/js/getUserMedia.js#L407-L431) the audio constraints are passed to the native code (getUserMedia.swift file) as an object but in that swift file they're trying do cast to _**string**_ , always is `nil` and the audio device doesn't change.
This PR fixes that bug.

Allowing audio devices change

---

src/PluginMediaStream.swift
src/PluginMediaStreamTrack.swift

Short term workarround for #480 
To test `bugs/MediaUUID` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/MediaUUID --verbose
```

Handle possible duplicate remote streamId/trackId with janus/kurento/freeswitch or short duplicate name

---

CHANGELOG.md
js/EventTarget.js
js/MediaStream.js
js/videoElementsHandler.js

See #494
Video to render when MediaStream fallback on Blob
Video does not render.
Run on iOS 10.3.1
* **Cordova version**:  8.1.2
* **Plugin version**:  6.0.9
* **iOS version**:  10.3.1
* **Xcode version**: 11.4 (11E146)
To test `bugs/Blob` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/Blob --verbose
```

Restore Blob only support for iOS 10.x that does not know MediaStream

---

extra/hooks/iosrtc-swift-support.js

To test `bugs/iosrtc-swift-support-env` branch
Test SWIFT_VERSION and IPHONEOS_DEPLOYMENT_TARGET config:
```
SWIFT_VERSION=5 IPHONEOS_DEPLOYMENT_TARGET=12 cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/iosrtc-swift-support-env --verbose
```
Test TEST_UNIFIED_BRIDGING_HEADER config:
```
TEST_UNIFIED_BRIDGING_HEADER=1 cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/iosrtc-swift-support-env --verbose
```
Test DISABLE_IOSRTC_HOOK config:
```
cordova plugin remove cordova-plugin-iosrtc …
```

add SWIFT_VERSION and IPHONEOS_DEPLOYMENT_TARGET and DISABLE_IOSRTC_HOOK env options for extra/hooks/iosrtc-swift-support.js

---

src/PluginRTCPeerConnection.swift

To test `bygs/onaddtrack-no-stream` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bygs/onaddtrack-no-stream --verbose
```
Note: 'bygs' yes typo sorry

handle peerConnection onaddtrack with no stream

---

src/PluginMediaStreamRenderer.swift

The image captured was the dimension of the container element and not the video element.

fix: use video view for correct screencap framing

---

dist/cordova-plugin-iosrtc.js
js/RTCPeerConnection.js

Fix #571
To test `bugs/addTrackSender ` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/addTrackSender --verbose
```

Fix RTCPeerConnection.addTrack should return sender 

---

src/PluginRTCPeerConnection.swift

This fixes issue #576. I am not sure if any more code should be moved. Basically if the getPluginStream can initialize a new MediaStream then it make sense to add that to the global media stream list that is in the iortcPlugin. So that when the javascript calls setListener on the MediaStreamTrack the track and the stream are available in the collection. Otherwise the call fails and javascript will never be notified of any of the events on the Track and consequently that track will not be displayed.
Risk this could have some other consequences if the PluginMediaStreams added here were never supposed to be added to the global collection.

Fixes issue #576 not found

---

.gitignore
src/PluginGetUserMedia.swift

When a cordova app is initially launched from XCode using this plugin and the device is in landscape orientation, the first video stream will have the wrong orientation.  I was able to recreate this issue using the sample app.  Let me know if there is a more appropriate `init`/`deinit` in which to place these calls, but get user media seemed appropriate to me.

fix: ensure proper orientation for first launch

---

js/MediaStreamRenderer.js
src/PluginMediaStreamRenderer.swift
www/cordova-plugin-iosrtc.js

reopening due to #580 being closed
~This adds a new subview to the webView which we ensure is always behind the webView and video views.~
In the refresh cycle it updates the background color, setting the alpha channel to 0 on the HTML video
and the Element View and element background color to the passed rgb value.

feat: use background-color from video element css

---

js/MediaStream.js
js/RTCPeerConnection.js
js/RTCStatsResponse.js
src/PluginMediaStream.swift
src/PluginMediaStreamTrack.swift
src/PluginRTCPeerConnection.swift
src/iosrtcPlugin.swift

The pull request fixes issue #592 the local and remote tracks not visible. The issue was Twilio parses the a=ssrc to get the exact trackIds mapped to the msid. this can seen here https://github.com/twilio/twilio-webrtc.js/blob/87f7e61106f58e29364999d8753c773e5602536f/lib/util/sdp.js#L127-L129 . 
There was also a problem after releasing the stream in which the stream id was not being removed from the RTCPeerConnection localtracks leading to the next time someone is trying to publish a track it would fail.

Fix MediaStreamTrack lifecycle and make GetStats logs silent.

---

js/MediaStream.js
js/RTCPeerConnection.js
src/PluginRTCPeerConnection.swift

fixes #606  connected streams should not be recycled as a reference is kept inside some webrtc libraries. The library will use the same MediaStream to publish another track if the user decides to do so causing an error of pluginMediaStream does not exist on the Swift side

removed calling checkActive for connected local streams

---

js/MediaStreamTrack.js
js/MediaTrackCapabilities.js
src/PluginGetUserMedia.swift
src/PluginMediaStreamTrack.swift
src/PluginRTCVideoCaptureController.swift
www/cordova-plugin-iosrtc.js

I hope I didn't miss/break something... Thanks in advance.

MediaStreamTrack: added getCapabilities().deviceId support for cam device media streams

---

src/PluginRTCAudioController.swift

Crash when the deviceId is not found.
Steps:
1. attach safari debugger
2. call `await navigator.mediaDevices.getUserMedia({audio:{deviceId: 'test'}})`

Fix gUM crash with invalid audio deviceId

---

src/PluginMediaStream.swift
src/PluginRTCPeerConnection.swift
src/iosrtcPlugin.swift

Check if pluginMediaStream had already the new track, otherwise add new track on PluginRTCPeerConnection ontrack.
This improve/fix Janus usage.
Tested using `cordova-plugin-iosrtc` with `www/index.html` modfied to use `js/index-janus.js`.
To test `task/janus` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#task/janus --verbose
```

Check if pluginMediaStream had already the new track, otherwise add new track on PluginRTCPeerConnection ontrack

---

js/MediaStream.js
js/MediaStreamTrack.js
js/RTCDataChannel.js
js/RTCPeerConnection.js
js/RTCRtpReceiver.js
js/RTCRtpSender.js
js/RTCRtpTransceiver.js
js/iosrtc.js
plugin.xml
src/PluginRTCPeerConnection.swift
src/PluginRTCRtpTransceiver.swift
src/iosrtcPlugin.swift
www/cordova-plugin-iosrtc.js

**Work in progress** Branch implementing the addTransceiver function. Created scaffolding so far and have some TODO comments sprinkled in the code that I will deal with next. 
Brief summary of things I need to deal with next (might have missed listing some):

WIP: Task/589/implement addtransceiver

---

src/iosrtcPlugin.swift

Fix will land in 6.0.22 aka 6 TLS and 8 aka master
> cordova plugin remove cordova-plugin-iosrtc --verbose
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bugs/RTCRequestPermissionnotDetermined --verbose

fix requestPermission returns true if AVAuthorizationStatus is notDetermined #690

---

js/RTCRtpSender.js
www/cordova-plugin-iosrtc.js

The problem is [new MediaStreamTrack(result.track)](https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/js/RTCRtpSender.js#L57) uses `MediaStreamTrack` module exports object instead of `MediaStreamTrack ` constructor.

RTCRtpSender: fixed MediaStreamTrack replace

---

src/PluginRTCPeerConnection.swift

According to https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/removeTrack `removeTrack` should not lead to `RTCRtpSender` remove.
This fixes `Cannot find native RTCRtpSender with id=xxxxx` on subsequent `RTCRtpSender.replaceTrack()` call

fixed RtpSenders inconsistency after removeTrack call

---

src/PluginGetDisplayMedia.swift
src/PluginRTCVideoCaptureController.swift

- Capturing the screen for a second time, did not work.
- Denying the consent crashed the app.

task/getDisplayMedia - 2 Bugfixes

---

src/PluginMediaStreamTrack.swift
src/PluginRTCPeerConnection.swift
src/PluginRTCRtpReceiver.swift
src/PluginRTCRtpSender.swift
src/PluginRTCRtpTransceiver.swift

fixes https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/734

Trying to fix issue with enable/disable track through receivers/senders list  with Janus Videoroom

---

js/iosrtc.js
www/cordova-plugin-iosrtc.js

#767 only contains changes to the compiled artifact and not the source - this is to add the same code so that `npm run build` won't lose the change.

add setDefaultAudioOutput to source

---

package.json
src/iosrtcPlugin.swift

I have addressed the issue of Null Pointer Exceptions in the iosrtcPlugin#RTCPeerConnection_RTCRtpSender_replaceTrack() method. I am using this plugin in a capacitor project where it can lead to app crashes without checking for nil values before accessing their properties.
Early Existence Checks: I have introduced early existence checks to ensure that critical objects, such as pluginRTCPeerConnection and pluginRTCRptSender, are not nil before attempting to use them.
Graceful Handling of Missing Objects: In case any of these objects are not found, I now emit error messages with informative details to assist with debugging and troubleshooting.
Safety for Optional Values: I have utilized Swift's optional binding (if let) to safely unwrap and use optional values like pluginMediaStreamTrack.

catch NPEs when calling replaceTrack

---

src/PluginRTCDTMFSender.swift

To test `bug/insertDTMF` branch
```
cordova plugin add https://github.com/cordova-rtc/cordova-plugin-iosrtc#bug/insertDTMF --verbose
```

fix PluginRTCDTMFSender insertDTMF when no senders is available
